import { useCallback, useEffect, useState } from 'react'
import { api } from '../../api'
import type { LearnedResponse, TimelineEntry } from '../../types'
import { formatWhen, isOutcomeEntry, parseExperience } from '../../lib/experiences'
import { ErrorState, Loading } from '../States'
import { AdminAsync, AdminBadge, AdminHeader, AdminPanel } from './AdminPanel'

/**
 * Organizational learning.
 *
 * This is the existing "What has EchoMind learned?" functionality, unchanged in
 * substance and now behind the admin session. It deliberately calls the same
 * `summarize_learning` the support organisation view used, so the admin
 * conclusion and the agent's own behaviour can never disagree.
 *
 * The summary is generated from retrieved organizational memory by the agent. It
 * is not a hand-written list, and the panel says so where the summary is shown.
 */
export default function LearningPanel() {
  const [learned, setLearned] = useState<LearnedResponse | null>(null)
  const [loadingLearned, setLoadingLearned] = useState(false)
  const [learnedError, setLearnedError] = useState<string | null>(null)

  const [timeline, setTimeline] = useState<TimelineEntry[]>([])
  const [loadingTimeline, setLoadingTimeline] = useState(true)
  const [timelineError, setTimelineError] = useState<string | null>(null)

  const summarise = useCallback(async () => {
    setLoadingLearned(true)
    setLearnedError(null)
    try {
      setLearned(await api.admin.learning())
    } catch (err) {
      setLearnedError(err instanceof Error ? err.message : String(err))
    } finally {
      setLoadingLearned(false)
    }
  }, [])

  useEffect(() => {
    const token = { cancelled: false }
    const start = async () => {
      try {
        const result = await api.admin.learningTimeline()
        if (token.cancelled) return
        setTimeline(result.entries)
        setTimelineError(null)
      } catch (err) {
        if (token.cancelled) return
        setTimelineError(err instanceof Error ? err.message : String(err))
      } finally {
        if (!token.cancelled) setLoadingTimeline(false)
      }
    }
    void start()
    return () => {
      token.cancelled = true
    }
  }, [])

  const learningEvents = timeline.length

  return (
    <>
      <AdminHeader
        eyebrow="Memory"
        title="Organizational Learning"
        lede="What EchoMind has accumulated from previous customer support experiences."
        actions={
          <button
            type="button"
            className="btn btn-primary btn-sm"
            onClick={() => void summarise()}
            disabled={loadingLearned}
          >
            {loadingLearned ? 'Thinking...' : learned ? 'Re-summarise memory' : 'Summarise memory'}
          </button>
        }
      />

      <AdminPanel
        title="What has EchoMind learned?"
        note={
          <>
            Generated by {`EchoMind`} from stored organizational memory on request. It is
            derived from what the organization has actually retained, not a manually written
            list, and it states only what the retrieved memories support.
          </>
        }
      >
        {loadingLearned && <Loading label="Reading organizational memory..." />}
        {!loadingLearned && learnedError && <ErrorState message={learnedError} onRetry={() => void summarise()} />}
        {!loadingLearned && !learnedError && learned?.summary && (
          <div className="learned-body">
            <p className="learned-summary">{learned.summary}</p>
            <p className="panel-note">
              Synthesised from {learned.memory_count} stored{' '}
              {learned.memory_count === 1 ? 'experience' : 'experiences'}.
            </p>
          </div>
        )}
        {!loadingLearned && !learnedError && learned && !learned.summary && (
          <div className="state state-empty">
            <p className="state-title">Nothing to summarise yet</p>
            <p className="state-text">
              Organizational memory is empty. Once a support interaction has been stored,
              EchoMind can summarise what the organization has learned.
            </p>
          </div>
        )}
        {!loadingLearned && !learnedError && !learned && (
          <div className="state state-empty">
            <p className="state-title">No summary generated in this session</p>
            <p className="state-text">
              Summarisation reads stored organizational memory through the agent, so it runs on
              request rather than on every page load.
            </p>
          </div>
        )}
      </AdminPanel>

      <AdminPanel
        title="Learning timeline"
        note="Chronological record of retained experience, newest first. Each entry became a lesson in organizational memory."
      >
        <AdminAsync
          loading={loadingTimeline}
          error={timelineError}
          isEmpty={!loadingTimeline && timeline.length === 0}
          empty="No learning events yet. Lessons appear here as outcomes are recorded."
          onRetry={() => window.location.reload()}
        >
          <>
            <p className="admin-count">
              {learningEvents} {learningEvents === 1 ? 'learning event' : 'learning events'}
            </p>
            <ol className="admin-timeline">
              {timeline.map((entry) => {
                const outcome = isOutcomeEntry(entry)
                const { problem, action } = parseExperience(entry.lessons)
                return (
                  <li className="admin-timeline-item" key={entry.id}>
                    <span
                      className={`admin-timeline-dot${outcome ? ' admin-timeline-dot-outcome' : ''}`}
                      aria-hidden="true"
                    />
                    <div className="admin-timeline-body">
                      <div className="admin-timeline-meta">
                        <AdminBadge tone={outcome ? 'approved' : 'live'}>
                          {outcome ? 'lesson' : 'interaction'}
                        </AdminBadge>
                        <span className="admin-timeline-when">{formatWhen(entry.occurred_at)}</span>
                        <span className="admin-timeline-customer">{entry.customer}</span>
                      </div>
                      <p className="admin-timeline-text">{problem || action || '-'}</p>
                    </div>
                  </li>
                )
              })}
            </ol>
          </>
        </AdminAsync>
      </AdminPanel>

      {learned && learned.memories.length > 0 && (
        <AdminPanel
          title="Memories behind this summary"
          note="The organizational memory that was retrieved to produce the summary above."
        >
          <ul className="admin-source-list">
            {learned.memories.map((memory, index) => {
              const record = memory as { text?: string; mentioned_at?: string }
              return (
                <li key={`${index}-${record.text?.slice(0, 12) ?? index}`}>
                  <p className="admin-source-text">{record.text ?? '-'}</p>
                  <p className="admin-source-when">{formatWhen(record.mentioned_at)}</p>
                </li>
              )
            })}
          </ul>
        </AdminPanel>
      )}
    </>
  )
}
